name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: pip install
        run: pip install -r requirements.txt

      - name: format
        run: python -m yapf -d --recursive hunter/ test/

      - name: unit tests
        run: python -m unittest discover test/
